version: "3"

tasks:
  download_dataset:
    cmds:
      - kaggle datasets download hearfool/vggface2
    status:
      - test -f vggface2.zip

  unzip_dataset:
    deps:
      - download_dataset
    cmds:
      - unzip -n vggface2.zip -d data/
      - find data/ -name '*.jpg' -size -8k -delete
    status:
      - test -d data/

  faces:
    deps:
      - unzip_dataset
    cmds:
      - python tasks.py faces
    status:
      - test -d faces

  parts:
    deps:
      - faces
    cmds:
      - python tasks.py parts
    status:
      - test -d noses

  download_dat:
    cmds:
      - wget https://github.com/GuoQuanhao/68_points/raw/refs/heads/master/shape_predictor_68_face_landmarks.dat

    status:
      - test -f shape_predictor_68_face_landmarks.dat
