version: "3"

tasks:
  download_dataset:
    cmds:
      - kaggle datasets download hearfool/vggface2
    generates:
      - vggface2.zip

  unzip_dataset:
    deps:
      - download_dataset
    cmds:
      - unzip vggface2.zip -d data/

  clean_dataset:
    deps:
      - download_dataset
    cmds:
      - find data/ -name '*.jpg' -size -8k -delete
